<div class="calcss">
	<h2>form</h2>
	<div class="row clearfix">
		<div class="col-md-6 column">	
			<form action="" name="form_height" method="POST" id="form_height">
				<span>Height</span>
				<input type="text" name="height" autocomplete="off" class="form-control input-md" />
				<span>Weight</span>
				<input type="text" name="weight" autocomplete="off" class="form-control input-md" />
				<input type="submit" name="calculate-total-submit" id="calculateTotalSubmit" autocomplete="off" class="form-control input-md" value="Calculate Total" />


			</form>



		</div>
	</div>
	<div id="calval" style="display: none;color: red">Output:
		<div><span>Total:</span> <span id="output"></span></div>
	</div>
</div>
