
<div class="owl-carousel owl-theme">
    <div class="item"><h4>1</h4></div>
    <div class="item"><h4>2</h4></div>
    <div class="item"><h4>3</h4></div>
    <div class="item"><h4>4</h4></div>
    <div class="item"><h4>5</h4></div>
    <div class="item"><h4>6</h4></div>
    <div class="item"><h4>7</h4></div>
    <div class="item"><h4>8</h4></div>
    <div class="item"><h4>9</h4></div>
    <div class="item"><h4>10</h4></div>
    <div class="item"><h4>11</h4></div>
    <div class="item"><h4>12</h4></div>
</div>


<button type="button" class="action" data-trigger="trigger">
    <span data-bind="i18n: 'Click Here'"></span>
</button>
<div data-bind="mageInit: {
'Magento_Ui/js/modal/modal':{
'type': 'popup',
'title': '',
'trigger': '[data-trigger=trigger]',
'responsive': true,
buttons: [{
    text: 'Ok',
    class: '',
    click: function() {
        this.closeModal();
    }
}]
}}" >

        <div class="modal-content" >
            <h4 class='modal-title'>
                <?=  __('Are you sure ?') ?>
            </h4>
            <select id="choose-add">
                <option value="0">-<?=  __('choose') ?>-</option>
                <option value="1"><?=  __('Yes') ?></option>
                <option value="2"><?=  __('No') ?></option>
            </select>
            <button class="action-modal">Submit</button>
        </div>

</div>
<hr/>
<div data-block="dropdown" class="minicart-wrapper">
    <button type="button" class="action" data-trigger="triggers">
        <span data-bind="i18n: 'Click Here'"></span>
    </button>
</div>
<div class="block block-minicart">
    <div id="minicart-content-wrapper">
        Here is our content
    </div>
</div>

<div style="clear:both;"></div>

<hr />

<script type="text/x-magento-init">
    {
        ".block-minicart": {
            "dropdownDialog": {
                "appendTo": "[data-block=dropdown]",
                "triggerTarget":"[data-trigger=triggers]",
                "timeout": 2000,
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "autoOpen": false,
                "triggerClass": "active",
                "parentClass": "active",
                "buttons": []
            }
        }
    }
</script>



<script>
    require([
        'jquery','owl1','owl2'], function ($) {
         $('.owl-carousel').owlCarousel({
            stagePadding: 50,
            loop:true,
            margin:30,
            nav:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:3
                },
                1000:{
                    items:5
                }
            }
        });


         $(".action-modal").on('click', function() {
              var a=$("#choose-add").children("option:selected").val();
                if(a==0){
                    alert("not");
                }else if(a==1){
                    alert("yes");
                }else{
                    alert("no");

                }


         });
     


     });
 </script>
